
version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

#################################
# Runtime Environment Variables #
#################################

# env:
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"

phases:
  install:
    commands:
      - echo "[+] Installing missing packages...."
      - apt-get update
      - apt-get install -y rsync
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "[Pre-Build phase]"
      - echo "[+] Running tests..."

  build:
    commands:
      - echo "[Build phase]"
      - echo "[+] doing nothing here ... test dummy"

  post_build:
    commands:
      - echo "[Post-Build phase]"
      - echo "Build completed on `date`"
