region: eu-central-1
stacks:
  fbo-ecs:
    template-url: templates/ecs-cluster.yaml
    parameters:
      SecurityGroup: '|ref|fbo-security-group.SecurityGroupId'

  fbo-task:
    template-url: templates/task.yaml
    parameters:
      Repository: '|ref|fbo-ecr.RepositoryUrl'
      ImageName: '|ref|fbo-ecr.RepositoryName'

  fbo-security-group:
    template-url: templates/sg.yaml
