region: eu-central-1
stacks:

   # The CI/CD Pipeline to build and deploy
   # atm. the service on ECS needed to be created manually
   fbo-pipeline:
      template-url: templates/pipeline.yaml
      parameters:
        DockerRepositoryUrl: '|ref|fbo-ecr.RepositoryUrl'
        DockerRepositoryName: '|ref|fbo-ecr.RepositoryName'
        ECSClusterName: '|ref|fbo-ecs.ClusterId'
        ECSServiceName: 'fbo'

   # Docker Repository to push and pull container images 
   fbo-ecr:
      template-url: templates/ecr.yaml
