region: eu-central-1
stacks:
   fbo-pipeline:
      template-url: templates/pipeline.yaml
      parameters:
        DockerRepositoryUrl: '|ref|fbo-ecr.RepositoryUrl'
        DockerRepositoryName: '|ref|fbo-ecr.RepositoryName'

   fbo-ecr:
      template-url: templates/ecr.yaml
