AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository

Resources:
  Repo:
    Type: "AWS::ECR::Repository"

Outputs:
  RepositoryName:
    Value: !Ref Repo
  RepositoryUrl:
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com'
