AWSTemplateFormatVersion: '2010-09-09'
Description: Task definition

Resources:
  Task:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        -
          Name: foo
          Cpu: 0
          PortMappings:
            -
              ContainerPort: 8000
              HostPort: 8000
          Memory: 500
          Image: !Sub '${AWS::AccountId}.dkr.ecr.eu-central-1.amazonaws.com/fbo:latest'
          Essential: true

Outputs:
  TaskArn:
    Value: !Ref Task
