AWSTemplateFormatVersion: '2010-09-09'
Description: Task definition

Parameters:

  Repository:
    Description: Repository URL
    Type: String
  ImageName:
    Description: Image Name in repository
    Type: String

Resources:
  Task:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        -
          Name: foo
          Cpu: 0
          PortMappings:
            -
              ContainerPort: 8000
              HostPort: 8000
          Memory: 500
          Image: !Sub '${Repository}/${ImageName}'
          Essential: true

Outputs:
  TaskArn:
    Value: !Ref Task
